[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['rm -f package-lock.json', 'npm install --no-package-lock']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'npm start'